"""
Backtracking runner: orchestrates the delayed-label intelligence loop (Issue #67).

When a new confirmed-black label is ingested, this runner:
1. Fetches newly confirmed vessels (since last_run_at checkpoint, or all)
2. Runs causal rewind — scans trailing 12 months for precursor signals
3. Runs label propagation — uplifts related entities via graph traversal
4. Writes a combined JSON report and a Markdown summary artifact

Regression safeguard: regression_checks.pass is True only when the number of
rewound vessels matches the number of confirmed vessels processed.

Usage:
    uv run python src/analysis/backtracking_runner.py --db data/processed/mpol.duckdb
    # incremental (process only labels confirmed since a checkpoint):
    uv run python scripts/run_backtracking.py --since 2026-01-01T00:00:00Z
"""

from __future__ import annotations

import argparse
import json
import os
from datetime import UTC, datetime
from typing import Any

import duckdb
import polars as pl
from dotenv import load_dotenv

from pipeline.src.analysis.causal_rewind import rewind_vessel
from pipeline.src.analysis.label_propagation import propagate_labels

load_dotenv()

DEFAULT_DB_PATH = os.getenv("DB_PATH", "data/processed/mpol.duckdb")
DEFAULT_OUTPUT_PATH = os.getenv(
    "BACKTRACKING_OUTPUT_PATH", "data/processed/backtracking_report.json"
)
DEFAULT_MD_OUTPUT_PATH = os.getenv(
    "BACKTRACKING_MD_OUTPUT_PATH", "data/processed/backtracking_report.md"
)
DEFAULT_REWIND_DAYS = 365


def _fetch_confirmed_since(
    db_path: str, since_utc: str | None, as_of_utc: str | None
) -> list[tuple[str, Any]]:
    as_of = as_of_utc or datetime.now(UTC).isoformat()
    con = duckdb.connect(db_path, read_only=True)
    try:
        if since_utc:
            df = con.execute(
                """
                SELECT mmsi, MAX(reviewed_at) AS confirmed_at
                FROM vessel_reviews
                WHERE review_tier = 'confirmed'
                  AND reviewed_at > ?
                  AND reviewed_at <= ?
                GROUP BY mmsi
                """,
                [since_utc, as_of],
            ).pl()
        else:
            df = con.execute(
                """
                SELECT mmsi, MAX(reviewed_at) AS confirmed_at
                FROM vessel_reviews
                WHERE review_tier = 'confirmed'
                  AND reviewed_at <= ?
                GROUP BY mmsi
                """,
                [as_of],
            ).pl()
    finally:
        con.close()
    if not df.is_empty() and df["confirmed_at"].dtype != pl.Datetime("us", "UTC"):
        df = df.with_columns(pl.col("confirmed_at").dt.convert_time_zone("UTC"))
    return [(r["mmsi"], r["confirmed_at"]) for r in df.iter_rows(named=True)]


def _render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Backtracking Report",
        "",
        f"**Generated:** {report['generated_at']}",
        f"**Confirmed vessels rewound:** {report['rewind']['vessel_count']}",
        f"**Propagated entities:** {report['propagation']['propagated_count']}",
        "",
        "## Precursor Signals",
        "",
    ]
    vessels = report["rewind"].get("vessels", [])
    if not vessels:
        lines.append("No confirmed vessels found in this run window.")
    else:
        for v in vessels:
            signals = v.get("precursor_signals", [])
            signal_str = (
                ", ".join(f"{s['feature']} (×{s['uplift_ratio']})" for s in signals)
                if signals
                else "none detected"
            )
            confirmed_short = str(v["confirmed_at"])[:10]
            lines.append(f"- **{v['mmsi']}** (confirmed {confirmed_short}): {signal_str}")

    lines += ["", "## Propagated Entities", ""]
    propagated = [v for v in report["propagation"].get("vessels", []) if v["hop"] > 0]
    if not propagated:
        lines.append("No related entities propagated.")
    else:
        for v in propagated:
            lines.append(
                f"- **{v['mmsi']}** ← {v['source_mmsi']} "
                f"via {v['evidence_type']} "
                f"(confidence {v['propagated_confidence']:.2f})"
            )

    rc = report["regression_checks"]
    status = "PASS" if rc["pass"] else "FAIL"
    lines += [
        "",
        "## Regression Checks",
        "",
        "| Check | Value |",
        "|---|---|",
        f"| Confirmed vessels | {rc['confirmed_vessel_count']} |",
        f"| Rewound vessels | {rc['rewind_vessel_count']} |",
        f"| Propagated entities | {rc['propagated_entity_count']} |",
        f"| Overall | **{status}** |",
        "",
        "---",
        "_Generated by arktrace backtracking runner (Issue #67)_",
    ]
    return "\n".join(lines)


def run_backtracking(
    db_path: str,
    output_path: str,
    md_output_path: str | None = None,
    since_utc: str | None = None,
    as_of_utc: str | None = None,
    rewind_days: int = DEFAULT_REWIND_DAYS,
) -> dict[str, Any]:
    """Run the full delayed-label intelligence loop.

    Args:
        db_path: Path to DuckDB database.
        output_path: Path for the JSON report artifact.
        md_output_path: Optional path for a Markdown summary artifact.
        since_utc: Incremental mode — only process labels confirmed after this timestamp.
        as_of_utc: Upper bound timestamp (defaults to now).
        rewind_days: How many days back to scan per confirmed vessel.

    Returns:
        Combined report dict.
    """
    generated_at = as_of_utc or datetime.now(UTC).isoformat()
    confirmed_rows = _fetch_confirmed_since(db_path, since_utc, as_of_utc)
    confirmed_mmsis = [r[0] for r in confirmed_rows]
    confirmed_at_map: dict[str, Any] = {r[0]: r[1] for r in confirmed_rows}

    # ── Causal rewind ────────────────────────────────────────────────────────
    vessel_rewind_results = []
    for mmsi, confirmed_at_raw in confirmed_at_map.items():
        confirmed_dt = (
            datetime.fromisoformat(confirmed_at_raw)
            if isinstance(confirmed_at_raw, str)
            else confirmed_at_raw
        )
        if confirmed_dt.tzinfo is None:
            confirmed_dt = confirmed_dt.replace(tzinfo=UTC)
        vessel_rewind_results.append(rewind_vessel(db_path, mmsi, confirmed_dt, rewind_days))

    rewind_section: dict[str, Any] = {
        "as_of_utc": generated_at,
        "rewind_days": rewind_days,
        "vessel_count": len(vessel_rewind_results),
        "vessels": vessel_rewind_results,
    }

    # ── Label propagation ────────────────────────────────────────────────────
    prop_df, prop_result = propagate_labels(db_path, as_of_utc)
    propagation_section: dict[str, Any] = {
        "seed_count": prop_result.seed_count,
        "propagated_count": prop_result.propagated_count,
        "total_vessels": prop_result.total_vessels,
        "as_of_utc": prop_result.as_of_utc,
        "vessels": prop_df.to_dicts(),
    }

    report: dict[str, Any] = {
        "generated_at": generated_at,
        "since_utc": since_utc,
        "new_confirmed_mmsis": confirmed_mmsis,
        "rewind": rewind_section,
        "propagation": propagation_section,
        "regression_checks": {
            "confirmed_vessel_count": len(confirmed_mmsis),
            "rewind_vessel_count": rewind_section["vessel_count"],
            "propagated_entity_count": prop_result.propagated_count,
            "pass": rewind_section["vessel_count"] == len(confirmed_mmsis),
        },
    }

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(report, f, indent=2, default=str)

    if md_output_path:
        md_content = _render_markdown(report)
        os.makedirs(os.path.dirname(md_output_path) or ".", exist_ok=True)
        with open(md_output_path, "w") as f:
            f.write(md_content)

    return report


def main() -> None:
    parser = argparse.ArgumentParser(description="Run delayed-label intelligence loop (Issue #67)")
    parser.add_argument("--db", default=DEFAULT_DB_PATH)
    parser.add_argument("--output", default=DEFAULT_OUTPUT_PATH)
    parser.add_argument("--md-output", default=DEFAULT_MD_OUTPUT_PATH)
    parser.add_argument(
        "--since",
        default=None,
        help="ISO timestamp: only process labels confirmed after this date (incremental mode)",
    )
    parser.add_argument("--as-of-utc", default=None)
    parser.add_argument("--rewind-days", type=int, default=DEFAULT_REWIND_DAYS)
    args = parser.parse_args()

    report = run_backtracking(
        db_path=args.db,
        output_path=args.output,
        md_output_path=args.md_output,
        since_utc=args.since,
        as_of_utc=args.as_of_utc,
        rewind_days=args.rewind_days,
    )
    rc = report["regression_checks"]
    status = "PASS" if rc["pass"] else "FAIL"
    print(
        f"Confirmed: {rc['confirmed_vessel_count']}, "
        f"Rewound: {rc['rewind_vessel_count']}, "
        f"Propagated: {rc['propagated_entity_count']}"
    )
    print(f"Regression check: {status}")
    print(f"Artifact: {args.output}")
    if args.md_output:
        print(f"Markdown: {args.md_output}")


if __name__ == "__main__":
    main()
