/**
 * Client-side alert ring buffer.
 *
 * Alerts are generated by diffing the vessel watchlist after each sync:
 *   - New MMSI appearing on the list  → "new" alert
 *   - Confidence increase ≥ 0.05      → "increase" alert
 *
 * The last 50 alerts are persisted in localStorage so they survive reloads.
 */

export type AlertKind = "new" | "increase";

export interface AlertEntry {
  id: string;
  timestamp: string;  // ISO 8601
  mmsi: string;
  vessel_name: string | null;
  confidence: number;
  delta: number | null;   // null for "new", positive number for "increase"
  kind: AlertKind;
  read: boolean;
}

const STORAGE_KEY = "arktrace_alerts";
const MAX_ALERTS = 50;

function load(): AlertEntry[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as AlertEntry[]) : [];
  } catch {
    return [];
  }
}

function save(entries: AlertEntry[]): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(entries));
  } catch {
    // Storage quota exceeded — silently ignore
  }
}

export function loadAlerts(): AlertEntry[] {
  return load();
}

export function markRead(id: string): AlertEntry[] {
  const entries = load().map((e) => (e.id === id ? { ...e, read: true } : e));
  save(entries);
  return entries;
}

export function markAllRead(): AlertEntry[] {
  const entries = load().map((e) => ({ ...e, read: true }));
  save(entries);
  return entries;
}

/** Diff two vessel lists and persist new alerts.  Returns updated list. */
export function diffAndAppend(
  prev: { mmsi: string; confidence: number; vessel_name?: string | null }[],
  next: { mmsi: string; confidence: number; vessel_name?: string | null }[],
): AlertEntry[] {
  const prevMap = new Map(prev.map((v) => [v.mmsi, v.confidence]));
  const now = new Date().toISOString();
  const newEntries: AlertEntry[] = [];

  for (const v of next) {
    const prevConf = prevMap.get(v.mmsi);
    if (prevConf === undefined) {
      // New vessel on watchlist
      newEntries.push({
        id: `${v.mmsi}-${Date.now()}`,
        timestamp: now,
        mmsi: v.mmsi,
        vessel_name: v.vessel_name ?? null,
        confidence: v.confidence,
        delta: null,
        kind: "new",
        read: false,
      });
    } else if (v.confidence - prevConf >= 0.05) {
      // Significant confidence increase
      newEntries.push({
        id: `${v.mmsi}-${Date.now()}`,
        timestamp: now,
        mmsi: v.mmsi,
        vessel_name: v.vessel_name ?? null,
        confidence: v.confidence,
        delta: v.confidence - prevConf,
        kind: "increase",
        read: false,
      });
    }
  }

  if (!newEntries.length) return load();

  const existing = load();
  const merged = [...newEntries, ...existing].slice(0, MAX_ALERTS);
  save(merged);
  return merged;
}
