/**
 * OPFS sync — download DuckLake Parquet files from arktrace-public into
 * the browser's Origin Private File System for offline use.
 *
 * Sync flow
 * ---------
 * 1. Fetch `ducklake_manifest.json` from R2 (lists all Parquet files + sizes).
 * 2. For each file in the manifest, check if it already exists in OPFS, the
 *    size matches, and the TTL has not expired.  Skip files that are fresh.
 * 3. Download missing/stale files from R2 and write them to OPFS along with a
 *    `.meta.json` sidecar recording the download timestamp.
 * 4. Load all OPFS-cached files into DuckDB-WASM as registered file buffers.
 *
 * The manifest is generated by `scripts/checkpoint_ducklake.py` and pushed to
 * `arktrace-public/ducklake_manifest.json` by `sync_r2.py push-ducklake-public`.
 */

import type { AsyncDuckDB } from "@duckdb/duckdb-wasm";
import { registerParquet } from "./duckdb";
import type { AppConfig } from "./config";

export const R2_BASE_URL = "https://arktrace-public.edgesentry.io";
// In dev, VITE_MANIFEST_URL can point to local fixture files served by Vite.
const MANIFEST_URL =
  import.meta.env.VITE_MANIFEST_URL ?? `${R2_BASE_URL}/ducklake_manifest.json`;

// Default TTL: 7 days. Override with VITE_CACHE_TTL_DAYS env var.
const CACHE_TTL_MS =
  Number(import.meta.env.VITE_CACHE_TTL_DAYS ?? 7) * 86_400_000;

export interface FileMeta {
  downloaded_at: string; // ISO-8601
}

export interface ManifestFile {
  /** R2 key relative to bucket root, e.g. "data/main/watchlist/ducklake-*.parquet" */
  key: string;
  /** Full URL for download */
  url: string;
  /** File size in bytes (used for staleness check) */
  size_bytes: number;
  /** DuckDB-WASM registration name, e.g. "watchlist.parquet" */
  register_as: string;
  /**
   * Optional region tag, e.g. "singapore".  When present, `syncAndLoad` can
   * filter downloads to only the requested regions.  Absent on combined files
   * that contain all regions — those are always downloaded.
   */
  region?: string;
  /**
   * When true, this file is only downloaded for authenticated (logged-in) users.
   * Non-authenticated clients skip it entirely.  Used for merged analyst review
   * files which must not leak to anonymous sessions.
   */
  private?: boolean;
}

export interface Manifest {
  generated_at: string;
  base_url: string;
  files: ManifestFile[];
}

export type SyncStatus =
  | { phase: "idle" }
  | { phase: "fetching_manifest" }
  | { phase: "syncing"; done: number; total: number; current: string }
  | { phase: "loading" }
  | { phase: "ready"; filesLoaded: number; fromCache: boolean; fromFixtures?: boolean; oldestCacheDate?: string }
  | { phase: "error"; message: string };

// ---------------------------------------------------------------------------
// OPFS helpers
// ---------------------------------------------------------------------------

async function getOpfsRoot(): Promise<FileSystemDirectoryHandle> {
  return navigator.storage.getDirectory();
}

async function opfsReadBuffer(name: string): Promise<ArrayBuffer | null> {
  try {
    const root = await getOpfsRoot();
    const fh = await root.getFileHandle(name);
    const file = await fh.getFile();
    return file.arrayBuffer();
  } catch {
    return null;
  }
}

async function opfsWriteBuffer(name: string, data: ArrayBuffer): Promise<void> {
  const root = await getOpfsRoot();
  const fh = await root.getFileHandle(name, { create: true });
  const writable = await fh.createWritable();
  await writable.write(data);
  await writable.close();
}

async function opfsFileSize(name: string): Promise<number | null> {
  try {
    const root = await getOpfsRoot();
    const fh = await root.getFileHandle(name);
    const file = await fh.getFile();
    return file.size;
  } catch {
    return null;
  }
}

async function opfsReadMeta(name: string): Promise<FileMeta | null> {
  const buf = await opfsReadBuffer(`${name}.meta.json`);
  if (!buf) return null;
  try {
    return JSON.parse(new TextDecoder().decode(buf)) as FileMeta;
  } catch {
    return null;
  }
}

async function opfsWriteMeta(name: string, meta: FileMeta): Promise<void> {
  const encoded = new TextEncoder().encode(JSON.stringify(meta));
  await opfsWriteBuffer(`${name}.meta.json`, encoded.buffer as ArrayBuffer);
}

/**
 * Returns true when the cached file should be re-downloaded.
 * Exported for unit testing.
 */
export function isStale(
  cachedSize: number | null,
  meta: FileMeta | null,
  manifestSize: number,
  ttlMs: number = CACHE_TTL_MS
): boolean {
  if (cachedSize !== manifestSize) return true;
  if (!meta) return true; // no sidecar → treat as expired (safe migration path)
  return Date.now() - new Date(meta.downloaded_at).getTime() > ttlMs;
}

// ---------------------------------------------------------------------------
// Manifest fetch
// ---------------------------------------------------------------------------

export async function fetchManifest(
  privateAuth?: boolean,
  config?: AppConfig,
  authToken?: string | null
): Promise<Manifest> {
  if (privateAuth && config) {
    const url = config.privateManifestUrl ?? MANIFEST_URL;
    const resp = await fetch(url, {
      cache: "no-store",
      ...(config.authProvider === "cloudflare-access"
        ? { credentials: "include", redirect: "manual" }
        : { headers: authToken ? { Authorization: `Bearer ${authToken}` } : {} }),
    });
    if (!resp.ok) throw new Error(`Failed to fetch manifest (${resp.status}): ${url}`);
    return resp.json() as Promise<Manifest>;
  }
  const resp = await fetch(MANIFEST_URL, { cache: "no-store", credentials: "omit" });
  if (!resp.ok) throw new Error(`Failed to fetch manifest (${resp.status}): ${MANIFEST_URL}`);
  return resp.json() as Promise<Manifest>;
}

// ---------------------------------------------------------------------------
// Sync
// ---------------------------------------------------------------------------

/**
 * Sync R2 Parquet files into OPFS, then register them with DuckDB-WASM.
 *
 * @param db        Initialised DuckDB-WASM instance.
 * @param onStatus  Called on every status change so the UI can show progress.
 * @param regions   Optional list of regions to download.  Files tagged with a
 *                  `region` field in the manifest are skipped unless their
 *                  region appears in this list.  Files with no region tag
 *                  (combined multi-region files) are always downloaded.
 *                  Pass `undefined` (default) to download everything.
 * @returns Number of files loaded into DuckDB.
 */
export async function syncAndLoad(
  db: AsyncDuckDB,
  onStatus: (s: SyncStatus) => void,
  regions?: string[],
  privateAuth?: boolean,
  config?: AppConfig,
  authToken?: string | null
): Promise<number> {
  // ── 1. Fetch manifest ───────────────────────────────────────────────────
  onStatus({ phase: "fetching_manifest" });
  let manifest: Manifest;
  try {
    manifest = await fetchManifest(privateAuth, config, authToken);
  } catch {
    // No network — try OPFS cache first, then bundled fixtures
    onStatus({ phase: "loading" });
    const fromOpfs = await loadFromOpfs(db);
    if (fromOpfs > 0) {
      onStatus({ phase: "ready", filesLoaded: fromOpfs, fromCache: true });
      return fromOpfs;
    }
    const fromFixtures = await loadFromFixtures(db);
    if (fromFixtures > 0) {
      onStatus({ phase: "ready", filesLoaded: fromFixtures, fromCache: true, fromFixtures: true });
      return fromFixtures;
    }
    onStatus({
      phase: "error",
      message: "No network and no cached data in OPFS. Connect to sync.",
    });
    return 0;
  }

  // ── 2. Download missing / stale files ───────────────────────────────────
  // Filter by region: skip files tagged for a different region than requested.
  // Files with no region tag are always included (they contain all regions).
  const wantedFiles = (regions
    ? manifest.files.filter((f) => !f.region || regions.includes(f.region))
    : manifest.files
  ).filter((f) => !f.private || privateAuth);

  const toDownload: ManifestFile[] = [];
  for (const f of wantedFiles) {
    const [cachedSize, meta] = await Promise.all([
      opfsFileSize(f.register_as),
      opfsReadMeta(f.register_as),
    ]);
    if (!isStale(cachedSize, meta, f.size_bytes)) continue;
    toDownload.push(f);
  }

  let done = 0;
  const downloadedAt = new Date().toISOString();
  for (const f of toDownload) {
    onStatus({
      phase: "syncing",
      done,
      total: toDownload.length,
      current: f.register_as,
    });
    try {
      const fetchUrl =
        privateAuth && config?.privateSigningEndpoint
          ? `${config.privateSigningEndpoint}?key=${encodeURIComponent(f.key)}`
          : f.url;
      const fetchOpts: RequestInit =
        privateAuth && config
          ? config.authProvider === "cloudflare-access"
            ? { credentials: "include", redirect: "manual" }
            : { headers: authToken ? { Authorization: `Bearer ${authToken}` } : {} }
          : { credentials: "omit" };
      const resp = await fetch(fetchUrl, fetchOpts);
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
      const buf = await resp.arrayBuffer();
      await opfsWriteBuffer(f.register_as, buf);
      await opfsWriteMeta(f.register_as, { downloaded_at: downloadedAt });
    } catch (err) {
      console.warn(`[opfs] Failed to download ${f.url}:`, err);
    }
    done++;
  }

  // ── 3. Load all wanted files into DuckDB-WASM from OPFS ────────────────
  onStatus({ phase: "loading" });
  let loaded = 0;
  let oldestCacheDate: string | undefined;
  for (const f of wantedFiles) {
    const buf = await opfsReadBuffer(f.register_as);
    if (!buf) continue;
    await registerParquet(db, f.register_as, buf);
    loaded++;
    const meta = await opfsReadMeta(f.register_as);
    if (meta && (!oldestCacheDate || meta.downloaded_at < oldestCacheDate)) {
      oldestCacheDate = meta.downloaded_at;
    }
  }

  onStatus({ phase: "ready", filesLoaded: loaded, fromCache: done === 0, oldestCacheDate });
  return loaded;
}

/**
 * Load bundled fixture Parquet files from /fixtures/ (served as static assets).
 * Last-resort fallback: no network + empty OPFS → still show demo data.
 */
async function loadFromFixtures(db: AsyncDuckDB): Promise<number> {
  const names = [
    "watchlist.parquet",
    "validation_metrics.parquet",
    "causal_effects.parquet",
    "score_history.parquet",
  ];
  let loaded = 0;
  for (const name of names) {
    try {
      const resp = await fetch(`/fixtures/${name}`);
      if (!resp.ok) continue;
      const buf = await resp.arrayBuffer();
      await registerParquet(db, name, buf);
      loaded++;
    } catch {
      // fixture file absent — skip
    }
  }
  return loaded;
}

/**
 * Load all `.parquet` files from OPFS into DuckDB-WASM without fetching from R2.
 * Used as fallback when offline and no manifest is available.
 */
async function loadFromOpfs(db: AsyncDuckDB): Promise<number> {
  let loaded = 0;
  // Well-known registration names used by checkpoint_ducklake.py
  const knownNames = [
    "watchlist.parquet",
    "composite_scores.parquet",
    "causal_effects.parquet",
    "validation_metrics.parquet",
  ];
  for (const name of knownNames) {
    const buf = await opfsReadBuffer(name);
    if (!buf) continue;
    await registerParquet(db, name, buf);
    loaded++;
  }
  return loaded;
}

// ---------------------------------------------------------------------------
// Storage quota
// ---------------------------------------------------------------------------

export async function getStorageEstimate(): Promise<{
  used: number;
  quota: number;
} | null> {
  if (!navigator.storage?.estimate) return null;
  const est = await navigator.storage.estimate();
  return { used: est.usage ?? 0, quota: est.quota ?? 0 };
}
